/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.util.Arrays;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author 50687
 */

public class Inicio extends javax.swing.JFrame {
     int Max[][];
    int Inicial[][];
    int Necesidad[][];
    int Disponibilidad[][];
    int countA = 0;
    int countM= 0; 
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        Inicial = new int [4][3];
        Max = new int[4][3]; // Suponiendo 4 procesos y 3 recursos como ejemplo
        Necesidad = new int[4][3];
        Disponibilidad = new int[4][3];
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Máximos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Disponibles = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Iniciales = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        Necesarios = new javax.swing.JTable();
        Enviar_iniciales = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Enviar_Max = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Proceso = new javax.swing.JTextField();
        Rec_inic1 = new javax.swing.JTextField();
        Rec_inic2 = new javax.swing.JTextField();
        Rec_inic3 = new javax.swing.JTextField();
        Rec_disp1 = new javax.swing.JTextField();
        Rec_max3 = new javax.swing.JTextField();
        Rec_max2 = new javax.swing.JTextField();
        Rec_max1 = new javax.swing.JTextField();
        Rec_disp3 = new javax.swing.JTextField();
        Rec_disp2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        respuesta = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Enviar_disponible = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Proceso");

        jLabel2.setText("Recurso 1");

        jLabel3.setText("Recurso 3");

        jLabel4.setText("Recurso 2");

        Máximos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A", "B", "C"
            }
        ));
        jScrollPane1.setViewportView(Máximos);

        Disponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A", "B", "C"
            }
        ));
        jScrollPane2.setViewportView(Disponibles);

        Iniciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "A", "B", "C"
            }
        ));
        jScrollPane3.setViewportView(Iniciales);
        Iniciales.getAccessibleContext().setAccessibleName("");
        Iniciales.getAccessibleContext().setAccessibleDescription("");

        Necesarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "A", "B", "C"
            }
        ));
        jScrollPane4.setViewportView(Necesarios);

        Enviar_iniciales.setText("Agregar recursos iniciales ");
        Enviar_iniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_inicialesActionPerformed(evt);
            }
        });

        jLabel5.setText("Recurso Iniciales");

        Enviar_Max.setText("Agregar Matriz Max");
        Enviar_Max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_MaxActionPerformed(evt);
            }
        });

        jLabel6.setText("Matriz de Máximo");

        jLabel7.setText("Recurso Disponibles");

        jLabel8.setText("Recurso Necesarios");

        Proceso.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_inic1.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_inic2.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_inic3.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_disp1.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_max3.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_max2.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_max1.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_disp3.setPreferredSize(new java.awt.Dimension(90, 22));

        Rec_disp2.setPreferredSize(new java.awt.Dimension(90, 22));

        respuesta.setColumns(20);
        respuesta.setRows(5);
        jScrollPane5.setViewportView(respuesta);

        jLabel9.setText("Maximo1");

        jLabel10.setText("Maximo 2");

        jLabel11.setText("Maximo 3");

        jLabel12.setText("Disponible 1");

        jLabel13.setText("Disponible 2");

        jLabel14.setText("Disponible 3");

        Enviar_disponible.setText("Agregar Matriz Disponibles");
        Enviar_disponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enviar_disponibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Rec_max1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Enviar_Max)
                                            .addComponent(Rec_max2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Enviar_disponible))
                                        .addGap(169, 169, 169))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(Rec_max3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(168, 168, 168))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Rec_disp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Rec_disp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(Rec_disp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(150, 150, 150))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(Rec_inic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(Rec_inic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Rec_inic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel10)
                                        .addGap(85, 85, 85)
                                        .addComponent(jLabel11))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(Enviar_iniciales))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(110, 110, 110)
                .addComponent(jLabel8)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Proceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rec_inic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rec_inic2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rec_inic3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addComponent(Enviar_iniciales)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Rec_max3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rec_max2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rec_max1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addComponent(Enviar_Max))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rec_disp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rec_disp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rec_disp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Enviar_disponible)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void imprimirMatriz(int[][] matriz) {
    // Implementación para imprimir una matriz en formato legible
}

private void imprimirVector(int[] vector) {
    // Implementación para imprimir un vector en formato legible
}

    private void Enviar_inicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_inicialesActionPerformed
        // TODO add your handling code here:
        String data1 = Proceso.getText();
        int data2 = Integer.parseInt(Rec_inic1.getText());
        int data3 = Integer.parseInt(Rec_inic2.getText());
        int data4 = Integer.parseInt(Rec_inic3.getText());
        Object[] row = {data1, data2, data3, data4};

        DefaultTableModel model = (DefaultTableModel) Iniciales.getModel();
        model.addRow(row);

        // Agregar datos a la matriz Inicial
        if (Inicial.length == 0) {
            Inicial = new int[1][countA];
        } else {
            Inicial = Arrays.copyOf(Inicial, Inicial.length + 1);
        }
        Inicial[countA] = new int[]{data2, data3, data4};
        int[][] newInicial = new int[Inicial.length + 1][Inicial[0].length];
        System.arraycopy(Inicial, 0, newInicial, 0, Inicial.length);
        newInicial[Inicial.length] = new int[] { data2, data3, data4 };
        Inicial= newInicial;
        countA++;
    
    }//GEN-LAST:event_Enviar_inicialesActionPerformed

    private void Enviar_MaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_MaxActionPerformed
        // TODO add your handling code here:
          try {
        int data1 = Integer.parseInt(Rec_max1.getText());
        int data2 = Integer.parseInt(Rec_max2.getText());
        int data3 = Integer.parseInt(Rec_max3.getText());

        Object[] row = {data1, data2, data3};
        DefaultTableModel model = (DefaultTableModel) Máximos.getModel();
        model.addRow(row);

        if (Max.length == 0) {
            Max = new int[1][3]; // 3 columnas para 3 recursos
        } else {
            Max = Arrays.copyOf(Max, Max.length + 1);
        }

        Max[countM] = new int[]{data1, data2, data3};
        countM++;
    } catch (NumberFormatException e) {
        respuesta.append("Error en el formato de los datos de la matriz Max.\n");
    }
    }//GEN-LAST:event_Enviar_MaxActionPerformed

    private void Enviar_disponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enviar_disponibleActionPerformed
        // TODO add your handling code here:
       try {
        int data1 = Integer.parseInt(Rec_disp1.getText());
        int data2 = Integer.parseInt(Rec_disp2.getText());
        int data3 = Integer.parseInt(Rec_disp3.getText());

        DefaultTableModel modelo = (DefaultTableModel) Disponibles.getModel();
        modelo.setRowCount(1);
        Disponibles.setValueAt(data1, 0, 0);
        Disponibles.setValueAt(data2, 0, 1);
        Disponibles.setValueAt(data3, 0, 2);

        
        Disponibilidad[0] = new int[]{data1, data2, data3};
        
        calcularNecesidad();
        ejecutarAlgoritmo();
    } catch (NumberFormatException e) {
        respuesta.append("Error en el formato de los datos de disponibilidad.\n");
    }
    }//GEN-LAST:event_Enviar_disponibleActionPerformed
public void calcularNecesidad(){
    if (countA == countM) {
        for (int i = 0; i < countA; i++) {
            for (int j = 0; j < 3; j++) {
                Necesidad[i][j] = Max[i][j] - Inicial[i][j];  
            }
        }
        
        DefaultTableModel modelo = (DefaultTableModel) Necesarios.getModel();
        modelo.setRowCount(0); 

        for (int i = 0; i < countA; i++) {
            Object[] fila = { Necesidad[i][0], Necesidad[i][1], Necesidad[i][2] };
            modelo.addRow(fila);
        }
    }
}
  public void ejecutarAlgoritmo() {
   
    System.out.println("Matriz Inicial:");
    imprimirMatriz(Inicial);
    System.out.println("Matriz Máxima:");
    imprimirMatriz(Max);
    System.out.println("Matriz de Disponibilidad:");
    System.out.println("Disponibilidad:");
for (int i = 0; i < Disponibilidad[0].length; i++) {
  System.out.print(Disponibilidad[0][i] + " ");
}
System.out.println();
    System.out.println("Matriz de Necesidades:");
    imprimirMatriz(Necesidad);
    calcularNecesidad();

    
    boolean[] finish = new boolean[countA]; 
    int[] work = Arrays.copyOf(Disponibilidad[0], Disponibilidad[0].length); 

    Arrays.fill(finish, false);

    boolean safe = true;

    
    boolean allFinished = false;
    while (!allFinished) {
        boolean found = false;
        for (int i = 0; i < countA; i++) {
            if (!finish[i]) {
                boolean can_execute = true;
                for (int j = 0; j < 3; j++) {
                    if (Necesidad[i][j] > work[j]) {
                        can_execute = false;
                        break;
                    }
                }
                if (can_execute) {
                    for (int j = 0; j < 3; j++) {
                        work[j] += Inicial[i][j];
                    }
                    finish[i] = true;
                    found = true;
                 
                    respuesta.append("Proceso " + i + " ha sido completado.\n");
                }
            }
        }
        
        allFinished = true;
        for (boolean b : finish) {
            if (!b) {
                allFinished = false;
                break;
            }
        }
        if (!found) {
            safe = false;
            break;
        }
    }

    if (safe) {
        respuesta.append("El sistema es seguro. Todos los procesos han sido completados.\n");
    } else {
        respuesta.append("El sistema está en un estado inseguro.\n");
    }
    
}




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Disponibles;
    private javax.swing.JButton Enviar_Max;
    private javax.swing.JButton Enviar_disponible;
    private javax.swing.JButton Enviar_iniciales;
    private javax.swing.JTable Iniciales;
    private javax.swing.JTable Máximos;
    private javax.swing.JTable Necesarios;
    private javax.swing.JTextField Proceso;
    private javax.swing.JTextField Rec_disp1;
    private javax.swing.JTextField Rec_disp2;
    private javax.swing.JTextField Rec_disp3;
    private javax.swing.JTextField Rec_inic1;
    private javax.swing.JTextField Rec_inic2;
    private javax.swing.JTextField Rec_inic3;
    private javax.swing.JTextField Rec_max1;
    private javax.swing.JTextField Rec_max2;
    private javax.swing.JTextField Rec_max3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea respuesta;
    // End of variables declaration//GEN-END:variables
}
